name: Test pip

on:
  push:
    # branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9, "pypy-3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -e .
      - name: PyTest
        # if: (! contains(matrix.python-version, 'pypy')) || contains(matrix.os, 'windows')
        run: |
          pip install pytest coverage
          coverage run --branch -m pytest
      - name: Black
        run: |
          pip install black
          black afar *.py --check --diff
      - name: Flake8
        if: (! contains(matrix.python-version, 'pypy'))
        run: |
          pip install flake8
          flake8 .
      - name: Coverage
        # if: (! contains(matrix.python-version, 'pypy'))
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version}}
          COVERALLS_PARALLEL: true
        run: |
          pip install coveralls
          coverage report --show-missing
          coveralls --service=github
      - name: Notebook test
        # if: (! contains(matrix.python-version, 'pypy'))
        run: |
          pip install nbconvert jupyter
          jupyter nbconvert --to notebook --execute afar/tests/*ipynb

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
